// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJK7Jlt3PARbDbVsuqTp-KT0GQhlR6V_c',
    appId: '1:263052502729:web:586c38c6845d7ffec00f18',
    messagingSenderId: '263052502729',
    projectId: 'appkevin-210b6',
    authDomain: 'appkevin-210b6.firebaseapp.com',
    storageBucket: 'appkevin-210b6.firebasestorage.app',
    measurementId: 'G-TDMXPB7MTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3tBySzuKnLYjrLkcqgNErG_zcVfbhrfk',
    appId: '1:263052502729:android:dce67f34feaa2222c00f18',
    messagingSenderId: '263052502729',
    projectId: 'appkevin-210b6',
    storageBucket: 'appkevin-210b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZnFRKwqcR_fY_DP8cxUTdNQDGUa64aQ',
    appId: '1:263052502729:ios:67fd6fe5b74daadbc00f18',
    messagingSenderId: '263052502729',
    projectId: 'appkevin-210b6',
    storageBucket: 'appkevin-210b6.firebasestorage.app',
    iosBundleId: 'com.example.appKevin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZnFRKwqcR_fY_DP8cxUTdNQDGUa64aQ',
    appId: '1:263052502729:ios:67fd6fe5b74daadbc00f18',
    messagingSenderId: '263052502729',
    projectId: 'appkevin-210b6',
    storageBucket: 'appkevin-210b6.firebasestorage.app',
    iosBundleId: 'com.example.appKevin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJK7Jlt3PARbDbVsuqTp-KT0GQhlR6V_c',
    appId: '1:263052502729:web:b9c432ade1bbd13fc00f18',
    messagingSenderId: '263052502729',
    projectId: 'appkevin-210b6',
    authDomain: 'appkevin-210b6.firebaseapp.com',
    storageBucket: 'appkevin-210b6.firebasestorage.app',
    measurementId: 'G-71YBBRRFL0',
  );
}
